### ISSUE TITLE
Req - 30: Store Docs in Browser memory

### ISSUE THREAD

**Issue by Fujio-Turner** [couchbaselabs/mobile-dart-flutter-plugin#31]
**WEB:**

object structure like this. Work in progress

```
Var db1 = {
”_default”:{
“_default”:{
	“foo”:{ “_meta”:{“_exp”:”unix-timestamp”} , “_rev”:1-11, ”some”:”data”},
	“foo2”:{“_rev”:2-22, ”some”:”data2”}
}
}
	  }
```

We need to know when and how much is too much. We'll find out in testing

What happens on open and close all tabs? 
 The whole browser? 
Can we safely put some data into browser cookies?
--If we cann't ,browser prevents cookies, how to handle UUID of replicator to prevent sg checkpoint spam

Try to keep the same words and phrases in a db.cblite2 table so if and when we convert to file based or sqlite it will be less work.

**Comment by dclark-disney** [comment]
WASM is supported in all the major browsers and there are DBs built using it which may solve this.

Some info:
* https://caniuse.com/wasm
* https://blog.ouseful.info/2022/02/11/sql-databases-in-the-browser-via-wasm-sqlite-and-duckdb/
* https://developer.chrome.com/blog/from-web-sql-to-sqlite-wasm/
* https://sqlite.org/wasm/doc/trunk/index.md

**Comment by Fujio-Turner** [comment]
Lets see what the true memory foot print is for the "cache" / object vs the JSON + meta Data.
