### ISSUE TITLE
Web Browser Support Matrix for Plugin version 1

### ISSUE THREAD

**Issue by Fujio-Turner** [couchbaselabs/mobile-dart-flutter-plugin#33]
Lets find out what version of the top 5 browser are most in use as of today. @Fujio-Turner

**Comment by Fujio-Turner** [comment]
Rank | Browser |  %
-- | -- | --
1 | Google Chrome 119 | 20.3% |  
2 | Safari Mobile 16 | 13.44% |  
3 | Google Chrome 118 | 11.29% |  
4 | Safari Mobile 17 | 8.15% |  
5 | Safari Mobile | 6.47% |  
6 | Firefox 119 | 6.41% |  
7 | Edge 119 | 4.75% |  
8 | Google Chrome 115 | 4.44% |  
9 | Safari 16.6 | 3.7% |  
10 | Edge 118 | 1.76% |  
11 | Safari 17.1 | 1.22% |  
12 | Safari 17.0.1 | 1.11% |  
13 | Safari Mobile 15 | 1.07% |  
14 | Google Chrome 117 | 1.04% |  

source: https://www.stetic.com/market-share/browser/


Chrome for Android is the most popular web/browser interface too.
source: https://gs.statcounter.com/browser-version-market-share

**Comment by ebenhaber** [comment]
Of course that is general web traffic. Here are the results from the PhoneHome data set of people using released versions of Couchbase 7.1 and 7.2  over the past 3 months: 

count	web_b
52725	"Chrome" (89%)
5033	"Firefox" (8.5%)
1660	"Safari". (2.8%)

I wonder what the distribution is on Capella.

**Comment by Fujio-Turner** [comment]
@jhilgedick-disney 
We are wanting to cover about 97-98% of all browser. Which should be about 10 or 11 of the above Web Browser. If you have different stats could you post it.

**Comment by Fujio-Turner** [comment]
Location of Capability Matrix: https://github.com/couchbaselabs/mobile-dart-flutter-plugin/wiki/Capability-Matrix
in Draft
