### ISSUE TITLE
Flutter Beta Support - 3.19 beta

### ISSUE THREAD

**Issue by dclark-disney** [couchbaselabs/mobile-dart-flutter-plugin#34]
While Flutter 3.16 is the latest stable, we are also planning to continue the testing of our code with betas. It would be good to have a version of this built on the latest beta as well which is currently 3.17 beta

**Comment by Fujio-Turner** [comment]
@dclark-disney. 

Here is the flutter beta versions notes and looks like they are one 3.19.x , as of Jan 29 , 2024
https://github.com/flutter/flutter/releases

Stable build is at 3.16.9. with a 7 Day release on the minor release , as of Jan 29 , 2024
https://flutter-ko.dev/development/tools/sdk/releases

I'm guessing by end of Feb they will be a 3.17.[3-4] build.

**Comment by dclark-disney** [comment]
Current highest beta is 3.19.0-0.3.pre as of this moment. By March, I think 3.19.0 will likely be released so we can target the current 3.19.0 beta.
