### ISSUE TITLE
Browser replication stops after 5 minutes

### ISSUE THREAD

**Issue by jhilgedick-disney** [couchbaselabs/mobile-dart-flutter-plugin#46]
Testing has gone well - but I've noticed that the example app begins to fail in the browser in a particular way.  

1. I start the example browser app (chrome) and the mobile app (either Android or iOS)
2. send messages back and forth for a few minutes
3. stop sending messages for 5 minutes
4. use the mobile app to send a message - message will NOT appear in the browser.
5. go to the browser app and attempt to send a message - message will be received by mobile app but will not be shown in the browser app.

I suspect this problem has nothing to do with replication and everything to do with a failure to properly update the message area above - but need to point it out.

I've attached the log files from the browser app.  An error is shown right away during startup. 
[browser-log-files.txt](https://github.com/user-attachments/files/16430039/browser-log-files.txt)
After the 5 minutes of no message sending, nothing appears in the log files for the browser.

**Comment by Fujio-Turner** [comment]
@jhilgedick-disney ,

Thanks for the logs. 
Let me get with the team and review.

**Comment by Jeff-Couchbase** [comment]
Hi @jhilgedick-disney , 

Currently fixing this issue to handle the connection during idle.

**Comment by Jeff-Couchbase** [comment]
Issue fixed handling idle issue on web. Check GA branch
